# -*- coding: utf-8 -*-
"""Dataset

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZlK1MAVKimNqVD5HC7CE66ZbC1DyLwk
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sbs

pb = pd.read_excel("/content/drive/MyDrive/Dataset/PIBEURO1casa.xlsx",index_col = 0, skipfooter = 4)

from google.colab import drive
drive.mount('/content/drive')

pb

pb.describe()

Covariância_da_Matriz = np.cov(pb)

Covariância_da_Matriz

autovalores, autovetores = np.linalg.eig((Covariância_da_Matriz))

autovalores #Automaticamente ordenados do maior para o menor

autovetores

df = pd.DataFrame(pb)

selection = df[['Belgium','Cyprus' ]]

selection

sbs.lineplot(x="Belgium", y="Cyprus",data = pb)
plt.show()
